'use client'
import {useState} from 'react'
type Member={id:string;name:string;email:string;status:string}
export default function TenantControls({tenantId,plan,subscriptionStatus,members}:{tenantId:string;plan:string;subscriptionStatus:string;members:Member[]}){
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
 async function act(payload:Record<string,unknown>){setBusy(true);setMessage('');try{const r=await fetch(`/api/admin/tenants/${tenantId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Operation failed');window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:'Operation failed')}finally{setBusy(false)}}
 function changePlan(value:string){const reason=window.prompt('Reason for plan change')?.trim();if(reason)void act({action:'plan',plan:value,reason})}
 function changeSubscription(value:string){const reason=window.prompt('Reason for subscription status change')?.trim();if(reason)void act({action:'subscription',status:value,reason})}
 function changeMember(memberId:string,value:string){const reason=window.prompt('Reason for member status change')?.trim();if(reason)void act({action:'member',memberId,status:value,reason})}
 return <div className="space-y-4 rounded-xl border p-4"><div><h2 className="font-semibold">Tenant administration</h2><p className="text-xs text-muted-foreground">Plan, subscription, and member controls are server-authorized and audited.</p></div><div className="flex flex-wrap gap-3"><label className="text-sm">Plan<select disabled={busy} value={plan} onChange={e=>changePlan(e.target.value)} className="ml-2 rounded-lg border bg-background px-2 py-2"><option>FREE</option><option>STARTER</option><option>BUSINESS</option><option>ENTERPRISE</option></select></label><label className="text-sm">Subscription<select disabled={busy} value={subscriptionStatus} onChange={e=>changeSubscription(e.target.value)} className="ml-2 rounded-lg border bg-background px-2 py-2"><option>ACTIVE</option><option>TRIALING</option><option>PAST_DUE</option><option>CANCELED</option><option>INCOMPLETE</option></select></label></div><div className="divide-y rounded-lg border">{members.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="text-sm font-medium">{m.name}</p><p className="text-xs text-muted-foreground">{m.email}</p></div><div className="flex items-center gap-2"><span className="text-xs">{m.status}</span><button disabled={busy} onClick={()=>changeMember(m.id,m.status==='ACTIVE'?'SUSPENDED':'ACTIVE')} className="rounded-lg border px-3 py-1.5 text-xs">{m.status==='ACTIVE'?'Suspend':'Reactivate'}</button></div></div>)}</div>{message&&<p className="text-sm text-destructive">{message}</p>}</div>
}
