'use client'

import { useEffect, useRef, useState } from 'react'

type Asset = { id:string; filename:string; mimeType:string; sizeBytes:string; url:string; width?:number|null; height?:number|null; createdAt:string }
export function PictureStudio({ workspaceId, points }: { workspaceId:string; points:number }) {
  const canvasRef=useRef<HTMLCanvasElement>(null); const [text,setText]=useState('Cloudie'); const [width,setWidth]=useState(1200); const [height,setHeight]=useState(630); const [cost,setCost]=useState<number|null>(null); const [assets,setAssets]=useState<Asset[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
  useEffect(()=>{void fetch(`/api/workspaces/${workspaceId}/billing/price?action=services.image_render`,{cache:'no-store'}).then(async r=>{const d=await r.json().catch(()=>null);if(r.ok)setCost(Number(d.amount))});void fetch(`/api/workspaces/${workspaceId}/assets`,{cache:'no-store'}).then(async r=>{const d=await r.json().catch(()=>null);if(r.ok)setAssets(d.assets??[])})},[workspaceId])
  function draw(){const canvas=canvasRef.current;if(!canvas)return;canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,width,height);ctx.fillStyle='#0f172a';ctx.font=`bold ${Math.max(36,Math.floor(width/16))}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text||'Cloudie',width/2,height/2);ctx.font='28px system-ui';ctx.fillStyle='#2563eb';ctx.fillText('Cloudie Picture Studio',width/2,height/2+70)}
  useEffect(draw,[text,width,height])
  async function render(){const canvas=canvasRef.current;if(!canvas||cost===null)return;if(points<cost)return setMessage(`Insufficient Points. You need ${cost} Points.`);setBusy(true);setMessage('');try{const dataUrl=canvas.toDataURL('image/png');const r=await fetch(`/api/workspaces/${workspaceId}/assets/render`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dataUrl,width,height,filename:`cloudie-${Date.now()}.png`,idempotencyKey:crypto.randomUUID()})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error??'Render failed');setMessage(`Rendered successfully. ${d.pointsCharged} Points charged.`);const refreshed=await fetch(`/api/workspaces/${workspaceId}/assets`,{cache:'no-store'});const list=await refreshed.json().catch(()=>null);if(refreshed.ok)setAssets(list.assets??[])}catch(e){setMessage(e instanceof Error?e.message:'Render failed')}finally{setBusy(false)}}
  return <section className="space-y-5"><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-2xl border bg-background p-4"><canvas ref={canvasRef} className="h-auto w-full rounded-xl border"/><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm sm:col-span-3"><span className="mb-1 block text-xs text-muted-foreground">Text</span><input value={text} onChange={e=>setText(e.target.value)} className="min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm"><span className="mb-1 block text-xs text-muted-foreground">Width</span><input type="number" min="320" max="4096" value={width} onChange={e=>setWidth(Number(e.target.value)||1200)} className="min-h-10 w-full rounded-lg border px-3"/></label><label className="text-sm"><span className="mb-1 block text-xs text-muted-foreground">Height</span><input type="number" min="240" max="4096" value={height} onChange={e=>setHeight(Number(e.target.value)||630)} className="min-h-10 w-full rounded-lg border px-3"/></label></div></div><aside className="rounded-2xl border bg-muted/30 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Render</p><p className="mt-2 text-2xl font-semibold">{cost===null?'—':`${cost.toLocaleString()} Points`}</p><p className="mt-1 text-sm text-muted-foreground">Balance: {points.toLocaleString()} Points</p><button onClick={render} disabled={busy||cost===null} className="mt-5 min-h-11 w-full rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground disabled:opacity-50">{busy?'Rendering…':'Render & save asset'}</button>{message&&<p role="status" className="mt-3 text-sm text-muted-foreground">{message}</p>}</aside></div><div><h3 className="font-semibold">Render library</h3><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{assets.map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border bg-background"><img src={a.url} alt={a.filename} className="aspect-video w-full object-cover"/><div className="p-3"><p className="truncate text-sm font-medium">{a.filename}</p><p className="mt-1 text-xs text-muted-foreground">{a.width&&a.height?`${a.width}×${a.height} · `:''}{new Date(a.createdAt).toLocaleString()}</p></div></a>)}{!assets.length&&<p className="text-sm text-muted-foreground">No rendered assets yet.</p>}</div></div></section>
}
