import { requireUser } from '@/lib/authorization'
import { prisma } from '@/lib/prisma'

export const dynamic='force-dynamic'

export default async function TicketingDocumentsPage(){
  const user=await requireUser()
  const membership=await prisma.workspaceMember.findFirst({where:{userId:user.id,status:'ACTIVE'},orderBy:{createdAt:'asc'},select:{workspaceId:true}})
  const rows=membership?await prisma.$queryRaw<Array<{id:string;type:string;title:string;documentId:string|null;pointsCharged:number;createdAt:Date}>>`SELECT "id","type","title","documentId","pointsCharged","createdAt" FROM "TicketingDocument" WHERE "userId"=${user.id} AND "workspaceId"=${membership.workspaceId} AND "documentId" IS NOT NULL ORDER BY "createdAt" DESC LIMIT 100`:[]
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm text-muted-foreground">Ticketing / Documents</p><h1 className="text-3xl font-semibold">Travel documents</h1><p className="mt-1 text-sm text-muted-foreground">Persisted PDF records generated by the internal Cloudie document engine.</p></div><section className="rounded-xl border bg-background"><div className="border-b p-4 font-medium">Document library</div><div className="divide-y">{rows.length?rows.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-medium">{row.title}</p><p className="text-xs text-muted-foreground">{row.type} · {row.pointsCharged} Points · {row.createdAt.toLocaleString()}</p></div><a className="rounded-lg border px-3 py-2 text-sm font-medium" href={`/api/ticketing/documents/${row.id}`}>Open / print</a></div>):<p className="p-6 text-sm text-muted-foreground">No generated documents yet.</p>}</div></section></div>
}
