import test from 'node:test'
import assert from 'node:assert/strict'
import { isPdf, renderPdf } from '../lib/pdf'

test('PDF renderer produces a valid non-empty PDF document', () => {
  const bytes = renderPdf({ title: 'Cloudie Invoice', fields: { Customer: 'Test Customer', Total: 'NGN 125,000.00' }, sections: [{ heading: 'Terms', body: 'Generated by the Cloudie document engine.' }] })
  assert.ok(bytes.byteLength > 200)
  assert.equal(isPdf(bytes), true)
  const text = new TextDecoder().decode(bytes)
  assert.match(text, /%PDF-1\.4/)
  assert.match(text, /Cloudie Invoice/)
  assert.match(text, /startxref/)
  assert.match(text, /%%EOF/)
})
