import { NextResponse } from 'next/server'
import { Prisma } from '@prisma/client'
import { requireWorkspaceMember } from '@/lib/authorization'
import { chargeForAction } from '@/lib/billing'
import { creditPoints } from '@/lib/points'
import { prisma } from '@/lib/prisma'
import { renderPdf } from '@/lib/pdf'
import { putPrivateObject, deletePrivateObject } from '@/lib/storage'

const types = new Set(['flight','hotel','invoice','receipt','itinerary','customs'])
const clean = (value: unknown, max = 4000) => typeof value === 'string' ? value.trim().slice(0, max) : ''

export async function POST(request: Request) {
  let charge: Awaited<ReturnType<typeof chargeForAction>> | null = null
  let workspaceId = ''
  let userId = ''
  let reference = ''
  try {
    const body = await request.json().catch(() => null) as Record<string, unknown> | null
    workspaceId = clean(body?.workspaceId, 100)
    const type = clean(body?.type, 30)
    const title = clean(body?.title, 180) || `Cloudie ${type} document`
    const idempotencyKey = clean(body?.idempotencyKey, 180)
    const payload = body?.payload && typeof body.payload === 'object' ? body.payload as Record<string, unknown> : {}
    if (!workspaceId || !types.has(type) || !idempotencyKey) return NextResponse.json({ error: 'workspaceId, type and idempotencyKey are required' }, { status: 400 })
    const { user } = await requireWorkspaceMember(workspaceId)
    userId = user.id
    const existing = await prisma.$queryRaw<Array<{ id:string; documentId:string|null; pointsCharged:number }>>(Prisma.sql`SELECT "id","documentId","pointsCharged" FROM "TicketingDocument" WHERE "idempotencyKey"=${idempotencyKey} LIMIT 1`)
    if (existing[0]) return NextResponse.json(existing[0])
    const action = `ticketing.${type}_pdf`
    reference = `ticketing:${idempotencyKey}`
    charge = await chargeForAction({ userId, workspaceId, action, description:`Generated ${type} PDF`, reference })
    let storageUrl: string | null = null
    let documentId: string | null = null
    try {
      const pdf = renderPdf({ title, subtitle:`${type.toUpperCase()} · Cloudie`, fields:Object.fromEntries(Object.entries(payload).filter(([_,v]) => typeof v === 'string' || typeof v === 'number').slice(0,30)), sections:[{heading:'Document record',body:'Generated by the Cloudie document engine.'}] })
      const storageKey = `generated/${user.id}/ticketing/${crypto.randomUUID()}.pdf`
      const bytes = pdf.buffer.slice(pdf.byteOffset, pdf.byteOffset + pdf.byteLength) as ArrayBuffer
      const stored = await putPrivateObject(storageKey, bytes, 'application/pdf')
      storageUrl = stored.url
      const doc = await prisma.document.create({ data:{workspaceId,ownerId:user.id,name:title,mimeType:'application/pdf',sizeBytes:BigInt(pdf.byteLength),storageKey:stored.pathname} })
      documentId = doc.id
      const id = crypto.randomUUID()
      await prisma.$executeRaw(Prisma.sql`INSERT INTO "TicketingDocument" ("id","workspaceId","userId","type","title","payload","documentId","pointsCharged","idempotencyKey") VALUES (${id},${workspaceId},${user.id},${type},${title},${JSON.stringify(payload)}::jsonb,${doc.id},${charge.amount},${idempotencyKey})`)
      await prisma.auditLog.create({ data:{userId:user.id,actorId:user.id,workspaceId,action:'TICKETING_DOCUMENT_GENERATED',entity:'TicketingDocument',entityId:id,metadata:{type,documentId:doc.id,pointsCharged:charge.amount}} })
      return NextResponse.json({id,documentId:doc.id,type,title,pointsCharged:charge.amount,storageKey:doc.storageKey},{status:201})
    } catch (error) {
      if (documentId) await prisma.document.delete({where:{id:documentId}}).catch(() => {})
      if (storageUrl) await deletePrivateObject(storageUrl).catch(() => {})
      if (charge.amount > 0 && !charge.idempotent) await creditPoints({userId,amount:charge.amount,description:`Refund for failed ${type} PDF generation`,reference:`${reference}:rollback`,workspace:workspaceId}).catch(() => {})
      throw error
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unable to generate document'
    const status = message.includes('Insufficient points') ? 402 : message.includes('access denied') || message.includes('Authentication') ? 401 : 500
    return NextResponse.json({error:message},{status})
  }
}
