import Link from 'next/link'
import { ArrowRight, Building2, Check, Globe2, Package, Plane, ShieldCheck, Sparkles, WalletCards } from 'lucide-react'

const features = [
  { title: 'Shipments', description: 'Create, assign, track and deliver with a complete operational timeline.', icon: Package },
  { title: 'Commerce', description: 'Connect products, vendors, orders and payments in one workspace.', icon: WalletCards },
  { title: 'Travel', description: 'Keep flight, hotel, booking and receipt workflows together.', icon: Plane },
  { title: 'Business tools', description: 'Run departments, staff, invoices and operational micro-apps.', icon: Building2 },
  { title: 'Digital services', description: 'Manage assets and documents with controlled access.', icon: Sparkles },
  { title: 'Secure by design', description: 'Tenant isolation, authorization, audit trails and private storage.', icon: ShieldCheck },
]

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b bg-background/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><Link href="/" className="text-xl font-black tracking-[-0.05em]">cloudie<span className="text-muted-foreground">.</span></Link><nav className="hidden items-center gap-6 text-sm font-medium text-muted-foreground md:flex"><Link href="#platform" className="hover:text-foreground">Platform</Link><Link href="#workspaces" className="hover:text-foreground">Workspaces</Link><Link href="#security" className="hover:text-foreground">Security</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="rounded-xl px-3 py-2 text-sm font-semibold hover:bg-muted">Sign in</Link><Link href="/register" className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm">Get started</Link></div></div></header>

    <section className="relative"><div className="pointer-events-none absolute left-1/2 top-0 -z-10 h-[520px] w-[900px] -translate-x-1/2 rounded-full bg-primary/5 blur-3xl" /><div className="mx-auto grid max-w-7xl gap-12 px-4 pb-24 pt-20 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:pb-32 lg:pt-28"><div><span className="inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1.5 text-xs font-semibold"><Globe2 className="size-3.5" /> One workspace for modern operations</span><h1 className="mt-7 max-w-4xl text-5xl font-semibold tracking-[-0.045em] sm:text-6xl lg:text-7xl">Everything your operation needs. <span className="text-muted-foreground">One Cloudie workspace.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Shipments, commerce, travel, business tools, digital services and a points ecosystem—connected to one secure account and built on your operational data.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground">Get started <ArrowRight className="size-4" /></Link><Link href="/track/" className="inline-flex min-h-12 items-center justify-center rounded-xl border px-5 font-semibold hover:bg-muted">Track a shipment</Link></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs font-medium text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Check className="size-3.5" /> Multi-workspace</span><span className="inline-flex items-center gap-1.5"><Check className="size-3.5" /> PostgreSQL-backed</span><span className="inline-flex items-center gap-1.5"><Check className="size-3.5" /> Role-based access</span></div></div><div className="rounded-[30px] border bg-card p-3 shadow-2xl shadow-black/5"><div className="rounded-[22px] border bg-muted/30 p-5 sm:p-6"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-muted-foreground">Cloudie overview</span><span className="rounded-full border bg-background px-2 py-1 text-[10px] font-semibold">LIVE DATA</span></div><div className="mt-6 rounded-2xl bg-primary p-5 text-primary-foreground"><p className="text-xs opacity-70">Available points</p><p className="mt-2 text-3xl font-semibold">Your wallet</p><div className="mt-6 h-2 rounded-full bg-primary-foreground/20"><div className="h-2 w-3/4 rounded-full bg-primary-foreground/80" /></div></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-2xl border bg-background p-4"><Package className="size-4" /><p className="mt-4 text-2xl font-semibold">Shipments</p><p className="mt-1 text-xs text-muted-foreground">Operational tracking</p></div><div className="rounded-2xl border bg-background p-4"><WalletCards className="size-4" /><p className="mt-4 text-2xl font-semibold">Wallet</p><p className="mt-1 text-xs text-muted-foreground">Atomic ledger</p></div></div></div></div></div></section>

    <section id="platform" className="border-y bg-muted/25"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-muted-foreground">The platform</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">A connected operating layer for your work.</h2><p className="mt-4 text-muted-foreground">Move from fragmented tools to one consistent place for customers, teams, money, documents and delivery operations.</p></div><div id="workspaces" className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(({ title, description, icon: Icon }) => <article key={title} className="rounded-2xl border bg-card p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className="inline-flex rounded-xl border bg-muted/40 p-2.5"><Icon className="size-5" /></span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></article>)}</div></div></section>

    <section id="security" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-muted-foreground">Built for control</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Your data stays inside clear authorization boundaries.</h2></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border p-5"><ShieldCheck className="size-5" /><p className="mt-4 text-sm font-semibold">Server-side authorization</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Workspace membership and ownership are validated on the server.</p></div><div className="rounded-2xl border p-5"><WalletCards className="size-5" /><p className="mt-4 text-sm font-semibold">Atomic points ledger</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Balance mutations are transaction-safe and idempotent.</p></div></div></div></section>

    <footer className="border-t"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© {new Date().getFullYear()} Cloudie</span><div className="flex gap-4"><Link href="/login" className="hover:text-foreground">Sign in</Link><Link href="/register" className="hover:text-foreground">Create account</Link></div></div></footer>
  </main>
}
