import Link from 'next/link'
import { prisma } from '@/lib/prisma'
import { requireSuperAdmin } from '@/lib/authorization'
export const dynamic='force-dynamic'
export default async function UsersAdmin({ searchParams }: { searchParams: Promise<{q?:string}> }) {
  await requireSuperAdmin(); const {q=''}=await searchParams
  const users=await prisma.user.findMany({where:q?{OR:[{email:{contains:q,mode:'insensitive'}},{name:{contains:q,mode:'insensitive'}},{id:{contains:q}}]}:undefined,orderBy:{createdAt:'desc'},take:100,select:{id:true,name:true,email:true,role:true,suspendedAt:true,createdAt:true,_count:{select:{pointLedger:true,shipmentsCreated:true,orders:true}}}})
  return <div className="mx-auto max-w-7xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold">Users</h1><p className="text-sm text-muted-foreground">Server-side search and operational account management.</p></div><form className="flex gap-2"><input name="q" defaultValue={q} placeholder="Search name, email or ID" className="h-10 rounded-lg border bg-background px-3 text-sm"/><button className="rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground">Search</button></form></div><div className="mt-6 overflow-x-auto rounded-xl border bg-background"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr>{['User','Role','Status','Joined','Activity'].map(x=><th key={x} className="p-3 font-medium">{x}</th>)}</tr></thead><tbody className="divide-y">{users.map(u=><tr key={u.id} className="hover:bg-muted/30"><td className="p-3"><Link className="font-medium hover:underline" href={`/admin/users/${u.id}`}>{u.name}</Link><div className="text-xs text-muted-foreground">{u.email}<br/>{u.id}</div></td><td className="p-3">{u.role}</td><td className="p-3">{u.suspendedAt?'SUSPENDED':'ACTIVE'}</td><td className="p-3 text-muted-foreground">{u.createdAt.toLocaleDateString()}</td><td className="p-3 text-xs">{u._count.pointLedger} ledger · {u._count.shipmentsCreated} shipments · {u._count.orders} orders</td></tr>)}</tbody></table>{!users.length&&<div className="p-8 text-center text-sm text-muted-foreground">No users found.</div>}</div></div>
}
