import { NextResponse } from 'next/server'
import { Prisma } from '@prisma/client'
import { requireWorkspaceMember } from '@/lib/authorization'
import { creditPoints } from '@/lib/points'
import { prisma } from '@/lib/prisma'
import { getCryptoProvider } from '@/lib/crypto/provider'

function pointsForAmount(amount:string){const rate=Number(process.env.CRYPTO_POINTS_PER_UNIT??1);if(!Number.isFinite(rate)||rate<=0)throw new Error('CRYPTO_POINTS_PER_UNIT is invalid');const points=Math.floor(Number(amount)*rate);if(!Number.isSafeInteger(points)||points<=0)throw new Error('Crypto deposit does not meet the configured points threshold');return points}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){try{const {id}=await context.params;const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const txHash=typeof body?.txHash==='string'?body.txHash.trim():'';if(!txHash)return NextResponse.json({error:'txHash is required'},{status:400});const deposit=(await prisma.$queryRaw<Array<{id:string;workspaceId:string;userId:string;asset:string;network:string;expectedAmount:string|null;status:string;txHash:string|null}>>(Prisma.sql`SELECT "id","workspaceId","userId","asset","network","expectedAmount","status","txHash" FROM "CryptoDeposit" WHERE "id"=${id} LIMIT 1`))[0];if(!deposit)return NextResponse.json({error:'Deposit not found'},{status:404});const {user}=await requireWorkspaceMember(deposit.workspaceId);if(user.id!==deposit.userId)return NextResponse.json({error:'Deposit access denied'},{status:403});if(deposit.status==='CONFIRMED')return NextResponse.json({ok:true,status:'CONFIRMED',txHash:deposit.txHash});const verified=await getCryptoProvider().verifyTransaction({txHash,asset:deposit.asset,network:deposit.network,expectedAmount:deposit.expectedAmount??undefined});if(verified.status==='REJECTED'||verified.status==='FAILED')return NextResponse.json({ok:false,status:verified.status,confirmations:verified.confirmations},{status:422});const points=verified.status==='CONFIRMED'?pointsForAmount(verified.expectedAmount??'0'):0;if(points>0)await creditPoints({userId:deposit.userId,amount:points,description:`Crypto deposit ${deposit.asset}`,reference:`crypto:${deposit.id}:confirmed`,workspace:deposit.workspaceId});await prisma.$executeRaw(Prisma.sql`UPDATE "CryptoDeposit" SET "txHash"=${txHash},"confirmations"=${verified.confirmations},"status"=${verified.status},"confirmedAt"=CASE WHEN ${verified.status}='CONFIRMED' THEN CURRENT_TIMESTAMP ELSE "confirmedAt" END,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${deposit.id} AND "status"<>'CONFIRMED'`);return NextResponse.json({ok:true,status:verified.status,confirmations:verified.confirmations,pointsCredited:points})}catch(error){const message=error instanceof Error?error.message:'Unable to verify crypto deposit';return NextResponse.json({error:message},{status:message.includes('Authentication')?401:message.includes('access denied')?403:503})}}
