'use client'
import { useEffect, useMemo, useState } from 'react'

const fields={
  flight:['Passenger name','Airline','Flight number','Departure airport','Arrival airport','Departure date/time','Arrival date/time','Booking/reference','Cabin/class','Baggage','Seat','Status','Notes'],
  hotel:['Guest name','Hotel','Address','Check-in','Check-out','Reservation number','Room type','Guests','Rate','Currency','Payment status','Status','Policies','Notes'],
  invoice:['Seller','Buyer','Invoice number','Invoice date','Due date','Seller address','Buyer address','Items','Quantity','Unit price','Taxes','Discount','Shipping','Subtotal','Total','Currency','Payment information','Status','Notes'],
  receipt:['Payer','Payee','Receipt number','Date','Amount','Currency','Payment method','Reference','Status','Description','Notes'],
  itinerary:['Passenger','Trip title','Departure','Arrival','Flight / transport','Departure date/time','Arrival date/time','Booking reference','Accommodation','Notes'],
  customs:['Shipper','Consignee','Goods','Quantities','Weights','Values','HS/customs information','Country of origin','Transport information','Declaration','Signature / authorization'],
}
type Type=keyof typeof fields
const presets:Record<Type,Record<string,string>>={flight:{'Status':'Confirmed','Cabin/class':'Economy'},hotel:{'Status':'Confirmed','Payment status':'Pending','Guests':'1'},invoice:{'Currency':'USD','Status':'Draft','Quantity':'1'},receipt:{'Currency':'USD','Status':'Paid'},itinerary:{'Trip title':'Cloudie travel itinerary'},customs:{'Country of origin':'United States'}}

export function TicketingBuilder({workspaceId}:{workspaceId:string}){
  const [type,setType]=useState<Type>('flight'); const [values,setValues]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [cost,setCost]=useState<number|null>(null); const [preview,setPreview]=useState(false)
  const list=useMemo(()=>fields[type],[type])
  useEffect(()=>{setCost(null);void fetch(`/api/workspaces/${workspaceId}/billing/price?action=ticketing.${type}_pdf`,{cache:'no-store'}).then(async r=>{const d=await r.json().catch(()=>null);if(r.ok)setCost(Number(d.amount))}).catch(()=>{})},[workspaceId,type])
  function choose(next:Type){setType(next);setValues(presets[next]);setPreview(false);setMessage('')}
  function previewDocument(){if(!Object.values(values).some(Boolean))return setMessage('Enter at least one document field before previewing.');setMessage('');setPreview(true)}
  async function generate(){setBusy(true);setMessage('');try{const r=await fetch('/api/ticketing/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,type,title:`Cloudie ${type} document`,payload:values,idempotencyKey:`ticketing-ui:${crypto.randomUUID()}`})});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.error??'Generation failed');setMessage(`Generated successfully. ${data.pointsCharged} Points charged.`);location.href=`/api/ticketing/documents/${data.id}`}catch(e){setMessage(e instanceof Error?e.message:'Generation failed')}finally{setBusy(false)}}
  return <div className="space-y-5"><div className="flex flex-wrap gap-2">{Object.keys(fields).map(x=><button key={x} onClick={()=>choose(x as Type)} className={`rounded-lg px-3 py-2 text-sm ${x===type?'bg-foreground text-background':'border bg-background'}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-muted/30 p-3"><span className="text-sm text-muted-foreground">Preset fields can be edited before generation. PDF billing occurs only after preview.</span><button onClick={()=>setValues(presets[type])} className="rounded-lg border bg-background px-3 py-2 text-xs font-medium">Reset preset</button></div>
    <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-xl border bg-background p-5"><div className="grid gap-3 sm:grid-cols-2">{list.map(label=><label key={label} className="text-sm"><span className="mb-1 block text-xs text-muted-foreground">{label}</span><input value={values[label]??''} onChange={e=>setValues(v=>({...v,[label]:e.target.value}))} className="min-h-10 w-full rounded-lg border bg-background px-3 py-2"/></label>)}</div><div className="mt-5 flex flex-wrap gap-3"><button onClick={previewDocument} disabled={busy} className="rounded-lg border px-4 py-2 text-sm font-medium">Preview</button><button disabled={busy||cost===null||!preview} onClick={generate} className="rounded-lg bg-foreground px-4 py-2 text-sm text-background disabled:opacity-50">{busy?'Generating…':`Generate PDF · ${cost===null?'…':`${cost} pts`}`}</button><button type="button" onClick={()=>window.print()} disabled={!preview} className="rounded-lg border px-4 py-2 text-sm font-medium disabled:opacity-50">Print preview</button></div>{message&&<p role="status" className="mt-3 rounded-lg bg-muted/50 p-3 text-sm">{message}</p>}</section>
      <aside className="rounded-xl border bg-muted/30 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Billing</p><p className="mt-2 text-2xl font-semibold">{cost===null?'—':`${cost.toLocaleString()} Points`}</p><p className="mt-1 text-sm text-muted-foreground">Charged only when the PDF is generated. Failed generation is refunded by the server.</p>{preview&&<div className="mt-5 rounded-xl border bg-background p-5 shadow-sm"><p className="text-xs text-muted-foreground">Print-ready preview</p><h2 className="mt-2 font-semibold">Cloudie {type} document</h2><div className="mt-4 space-y-2 text-sm">{Object.entries(values).filter(([,v])=>v).map(([k,v])=><div key={k} className="flex justify-between gap-4 border-b pb-2"><span className="text-muted-foreground">{k}</span><span className="text-right font-medium">{v}</span></div>)}</div></div>}</aside></div></div>
}
