'use client'
import { useMemo, useState } from 'react'

export default function ServicesUtilitiesPage(){
  const [amount,setAmount]=useState('100'),[rate,setRate]=useState('1.08'),[from,setFrom]=useState('USD'),[to,setTo]=useState('EUR')
  const [bytes,setBytes]=useState('1048576')
  const converted=useMemo(()=>{const n=Number(amount),r=Number(rate);return Number.isFinite(n)&&Number.isFinite(r)?(n*r).toFixed(2):'—'},[amount,rate])
  const mb=useMemo(()=>{const n=Number(bytes);return Number.isFinite(n)?(n/1048576).toFixed(2):'—'},[bytes])
  return <div className="mx-auto max-w-5xl space-y-6"><div><p className="text-sm text-muted-foreground">Workspace / Services / Utilities</p><h1 className="text-3xl font-semibold">Utilities</h1><p className="mt-1 text-sm text-muted-foreground">Local utility tools. Calculations run in the browser and do not create billable records.</p></div><div className="grid gap-5 md:grid-cols-2"><section className="rounded-xl border bg-background p-5"><h2 className="font-medium">Currency calculator</h2><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm">Amount<input value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border px-3" /></label><label className="text-sm">Rate<input value={rate} onChange={e=>setRate(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border px-3" /></label><label className="text-sm">From<select value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border px-3"><option>USD</option><option>EUR</option><option>GBP</option><option>NGN</option></select></label><label className="text-sm">To<select value={to} onChange={e=>setTo(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border px-3"><option>EUR</option><option>USD</option><option>GBP</option><option>NGN</option></select></label></div><p className="mt-5 text-2xl font-semibold">{converted} {to}</p><p className="text-xs text-muted-foreground">Manual rate: 1 {from} = {rate} {to}</p></section><section className="rounded-xl border bg-background p-5"><h2 className="font-medium">Data size calculator</h2><label className="mt-4 block text-sm">Bytes<input value={bytes} onChange={e=>setBytes(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border px-3" /></label><p className="mt-5 text-2xl font-semibold">{mb} MiB</p><p className="text-xs text-muted-foreground">Binary conversion: bytes ÷ 1,048,576.</p></section></div></div>
}
