'use client'
import { useEffect, useState } from 'react'

type Dispute = { id:string; orderId:string; reason:string; description:string; status:string; resolution:string|null; openedByEmail:string; orderStatus:string; paymentStatus:string; total:string|number }
export default function DisputesAdmin() {
  const [items,setItems]=useState<Dispute[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState('')
  async function load(){ const r=await fetch('/api/admin/disputes',{cache:'no-store'}); const d=await r.json(); if(!r.ok)return setError(d.error||'Unable to load disputes'); setItems(d.items||[]) }
  useEffect(()=>{void load()},[])
  async function resolve(disputeId:string,action:'resolve'|'refund'){ const resolution=window.prompt(action==='refund'?'Refund resolution note':'Resolution note')?.trim(); if(!resolution)return; setBusy(disputeId); const r=await fetch('/api/admin/disputes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({disputeId,action,resolution})}); const d=await r.json(); setBusy(''); if(!r.ok)setError(d.error||'Operation failed'); else await load() }
  return <main className="mx-auto max-w-7xl space-y-6 p-6"><div><h1 className="text-3xl font-semibold">Disputes</h1><p className="mt-1 text-sm text-muted-foreground">Resolve marketplace disputes. Refund resolution updates the internal order/payment state; it does not claim to execute an external processor refund.</p></div>{error&&<div className="rounded-lg border border-red-300 p-3 text-sm">{error}</div>}<div className="space-y-3">{items.map(x=><article key={x.id} className="rounded-xl border bg-background p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-semibold">{x.reason}</p><p className="text-xs text-muted-foreground">{x.id} · order {x.orderId} · {x.openedByEmail}</p><p className="mt-2 text-sm">{x.description}</p></div><div className="text-right text-sm"><p>{x.status}</p><p>{String(x.total)} · {x.paymentStatus}</p></div></div>{x.status==='OPEN'||x.status==='UNDER_REVIEW'?<div className="mt-4 flex gap-2"><button disabled={busy===x.id} onClick={()=>void resolve(x.id,'resolve')} className="rounded-lg border px-3 py-2 text-sm">Resolve</button><button disabled={busy===x.id} onClick={()=>void resolve(x.id,'refund')} className="rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground">Resolve & mark refunded</button></div>:<p className="mt-4 text-xs text-muted-foreground">{x.resolution||'Resolved'}</p>}</article>)}{!items.length&&<div className="rounded-xl border p-8 text-center text-sm text-muted-foreground">No disputes found.</div>}</div></main>
}
