'use client'
import { useEffect, useState } from 'react'

export default function ServicesTemplatesPage(){
  const [workspaceId,setWorkspaceId]=useState(''),[templates,setTemplates]=useState<Array<{id:string;name:string;documentType:string;version:number|null}>>([]),[name,setName]=useState(''),[type,setType]=useState('invoice'),[message,setMessage]=useState('')
  async function load(id:string){const r=await fetch(`/api/workspaces/${id}/document-templates`,{cache:'no-store'});const d=await r.json().catch(()=>null);if(r.ok)setTemplates(Array.isArray(d?.templates)?d.templates:[]);else setMessage(d?.error??'Unable to load templates')}
  useEffect(()=>{fetch('/api/workspaces',{cache:'no-store'}).then(r=>r.json()).then(d=>{const id=d?.workspaces?.[0]?.id;if(id){setWorkspaceId(id);void load(id)}}).catch(()=>{})},[])
  async function create(){if(!workspaceId||!name.trim())return;const r=await fetch(`/api/workspaces/${workspaceId}/document-templates`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:name.trim(),documentType:type,content:{title:name.trim(),body:'Editable Cloudie template content'}})});const d=await r.json().catch(()=>null);if(!r.ok){setMessage(d?.error??'Unable to create template');return}setName('');setMessage('Template created.');void load(workspaceId)}
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm text-muted-foreground">Workspace / Services / Templates</p><h1 className="text-3xl font-semibold">Templates</h1><p className="mt-1 text-sm text-muted-foreground">Workspace-scoped document templates backed by Cloudie storage.</p></div><section className="rounded-xl border bg-background p-5"><div className="flex flex-wrap gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Template name" className="min-h-10 flex-1 rounded-lg border px-3"/><select value={type} onChange={e=>setType(e.target.value)} className="min-h-10 rounded-lg border px-3"><option>invoice</option><option>itinerary</option><option>receipt</option><option>customs</option></select><button onClick={create} className="rounded-lg bg-foreground px-4 py-2 text-sm text-background">Create</button></div>{message&&<p className="mt-3 text-sm text-muted-foreground">{message}</p>}</section><section className="grid gap-4 md:grid-cols-3">{templates.map(t=><article key={t.id} className="rounded-xl border bg-background p-5"><p className="font-medium">{t.name}</p><p className="mt-1 text-xs text-muted-foreground">{t.documentType} · v{t.version??1}</p></article>)}</section></div>
}
