import Link from 'next/link'
import { requireSuperAdmin } from '@/lib/authorization'
import { prisma } from '@/lib/prisma'
export const dynamic='force-dynamic'
const titles:Record<string,string>={marketplace:'Marketplace',orders:'Orders',disputes:'Disputes',transactions:'Wallet & Ledger',shipments:'Shipments',documents:'Documents',tenants:'Business Tenants',notifications:'Notifications',audit:'Audit Logs',analytics:'Analytics','system-health':'System Health',pricing:'Pricing',settings:'Settings'}
export default async function AdminSection({params}:{params:Promise<{section:string}>}){await requireSuperAdmin();const {section}=await params;const title=titles[section]??'Administration';let rows:{id:string;label:string;meta:string}[]=[]
if(section==='orders'){const x=await prisma.order.findMany({orderBy:{createdAt:'desc'},take:100,include:{workspace:{select:{name:true}},user:{select:{name:true,email:true}},items:{include:{product:{select:{name:true}}}}}});rows=x.map(o=>({id:o.id,label:o.user?.name||o.customerId||'Guest',meta:`${o.status} · ${o.total.toString()} · ${o.workspace.name}`}))}
if(section==='shipments'){const x=await prisma.shipment.findMany({orderBy:{createdAt:'desc'},take:100,include:{workspace:{select:{name:true}}}});rows=x.map(s=>({id:s.id,label:s.trackingId,meta:`${s.status} · ${s.origin} → ${s.destination} · ${s.workspace.name}`}))}
if(section==='documents'){const x=await prisma.document.findMany({orderBy:{createdAt:'desc'},take:100});rows=x.map(d=>({id:d.id,label:d.name,meta:`${d.mimeType} · ${d.sizeBytes.toString()} bytes · ${d.workspaceId}`}))}
if(section==='notifications'){const x=await prisma.notification.findMany({orderBy:{createdAt:'desc'},take:100,include:{user:{select:{name:true,email:true}}}});rows=x.map(n=>({id:n.id,label:n.title,meta:`${n.type} · ${n.user.email} · ${n.createdAt.toLocaleString()}`}))}
if(section==='audit'){const x=await prisma.auditLog.findMany({orderBy:{createdAt:'desc'},take:200});rows=x.map(a=>({id:a.id,label:a.action,meta:`${a.entity}${a.entityId?`/${a.entityId}`:''} · ${a.result} · ${a.createdAt.toLocaleString()}`}))}
if(section==='analytics'){const [users,active,shipments,delivered,orders,docs,workspaces,ledger]=await Promise.all([prisma.user.count(),prisma.user.count({where:{suspendedAt:null}}),prisma.shipment.count(),prisma.shipment.count({where:{status:'DELIVERED'}}),prisma.order.count(),prisma.document.count(),prisma.workspace.count(),prisma.pointLedger.aggregate({_sum:{amount:true}})]);rows=[['Users',users],['Active users',active],['Shipments',shipments],['Delivered shipments',delivered],['Orders',orders],['Documents',docs],['Tenants',workspaces],['Net points',ledger._sum.amount??0]].map(([label,value])=>({id:String(label),label:String(label),meta:Number(value).toLocaleString()}))}
if(section==='system-health'){const [jobs]=await Promise.all([prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*)::bigint AS count FROM "CloudieJob" WHERE status = 'FAILED'`]);const failed=Number(jobs[0]?.count??0);rows=[{id:'database',label:'PostgreSQL database',meta:'Live query completed'},{id:'application',label:'Application authorization',meta:'Server-side admin authorization active'},{id:'jobs',label:'Background jobs',meta:failed?`${failed} failed`:'No failed jobs'}]}
if(section==='tenants'){const x=await prisma.workspace.findMany({orderBy:{createdAt:'desc'},take:200,include:{owner:{select:{name:true,email:true}},members:{select:{id:true,status:true}}}});rows=x.map(w=>({id:w.id,label:w.name,meta:`${w.plan} · ${w.subscriptionStatus} · ${w.members.length} members · owner ${w.owner.email}`}))}
if(section==='pricing'){const x=await prisma.pointPricingRule.findMany({orderBy:{createdAt:'desc'},take:100});rows=x.map(p=>({id:p.id,label:p.action,meta:`${p.pointCost} points · ${p.enabled?'ACTIVE':'DISABLED'} · ${p.reason}`}))}
if(section==='settings')rows=[{id:'security',label:'Security',meta:'Server-side authorization and HTTP-only Better Auth sessions'},{id:'configuration',label:'Configuration',meta:'Secrets remain in deployment environment; never rendered in plaintext'}]
return <div className="mx-auto max-w-7xl"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">Production data only. No placeholder records are presented.</p></div><div className="mt-6 overflow-x-auto rounded-xl border bg-background"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr><th className="p-3">Resource</th><th className="p-3">Details</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}>{section==='tenants'?<td className="p-3 font-medium"><Link className="hover:underline" href={`/admin/tenants/${r.id}`}>{r.label}</Link></td>:<td className="p-3 font-medium">{r.label}</td>}<td className="p-3 text-muted-foreground">{r.meta}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-8 text-center text-sm text-muted-foreground">No records found.</div>}</div><div className="mt-4"><Link href="/admin" className="text-sm text-primary hover:underline">← Back to dashboard</Link></div></div>}
